import AddOutlinedIcon from '@mui/icons-material/AddOutlined'
import { zodResolver } from '@hookform/resolvers/zod'
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, MenuItem, Paper, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import dayjs from 'dayjs'
import { useState } from 'react'
import { Controller, useForm } from 'react-hook-form'
import { z } from 'zod'
import { useAuth } from '../../hooks/useAuth'
import { transactionService } from '../../services/transactionService'
import { PaymentMode, TransactionType } from '../../types/transaction'
import type { Transaction, TransactionInput } from '../../types/transaction'
import { UserRole } from '../../types/auth'
import './TransactionsPage.css'
import EditOutlinedIcon from '@mui/icons-material/EditOutlined';
import DeleteIcon from '@mui/icons-material/Delete';

const schema = z.object({ person: z.string().min(1), type: z.enum([TransactionType.Deposit, TransactionType.Withdrawal]), amount: z.coerce.number().positive('Enter an amount greater than zero.'), date: z.string().min(1), mode: z.enum([PaymentMode.OnlineTransfer, PaymentMode.Cash]), note: z.string(), }).refine((data) => data.type !== TransactionType.Withdrawal || Boolean(data.note.trim()), { message: 'A withdrawal note is required.', path: ['note'] })
const defaultValues: TransactionInput = { person: '', type: TransactionType.Deposit, amount: 0, date: dayjs().format('YYYY-MM-DD'), mode: PaymentMode.OnlineTransfer, note: '' }
export function TransactionsPage() { const { user, idToken } = useAuth(); const client = useQueryClient(); const [editing, setEditing] = useState<Transaction | null>(null); const [open, setOpen] = useState(false); const query = useQuery({ queryKey: ['transactions'], queryFn: () => transactionService.list(idToken!), enabled: Boolean(idToken) }); const invalidate = () => client.invalidateQueries({ queryKey: ['transactions'] }); const save = useMutation({ mutationFn: (data: TransactionInput) => editing ? transactionService.update(idToken!, editing.id, data) : transactionService.create(idToken!, data), onSuccess: () => { setOpen(false); setEditing(null); invalidate() } }); const remove = useMutation({ mutationFn: (id: string) => transactionService.remove(idToken!, id), onSuccess: invalidate }); const canManage = user?.role === UserRole.Admin; const startCreate = () => { setEditing(null); setOpen(true) }; const startEdit = (transaction: Transaction) => { setEditing(transaction); setOpen(true) }; return <section className="transactions-page"><div className="transactions-page__heading"><div><Typography component="h1" variant="h1">Transactions</Typography><Typography color="text.secondary">Deposits and expenses recorded in your family ledger.</Typography></div><Button onClick={startCreate} startIcon={<AddOutlinedIcon />} variant="contained">Add transaction</Button></div>{query.isError && <Alert severity="error">{query.error.message}</Alert>}{query.isLoading ? <Typography>Loading transactions…</Typography> : <Paper className="transactions-table">{query.data?.length ? query.data.map((transaction) => <article className="transaction-row" key={transaction.id}><div><Typography sx={{ fontWeight: 700 }}>{transaction.person}</Typography><Typography color="text.secondary" variant="body2">{transaction.date} · {transaction.mode.replace('_', ' ')}</Typography></div><Typography className={transaction.type === TransactionType.Deposit ? 'amount amount--deposit' : 'amount amount--withdrawal'}>{transaction.type === TransactionType.Deposit ? '+' : '-'} ₹{Number(transaction.amount).toLocaleString('en-IN')}</Typography><Typography className="transaction-note" color="text.secondary">{transaction.note || '–'}</Typography>{canManage && <div><IconButton aria-label="Edit transaction" onClick={() => startEdit(transaction)}><EditOutlinedIcon /></IconButton><IconButton aria-label="Delete transaction" onClick={() => { if (window.confirm('Delete this transaction?')) remove.mutate(transaction.id) }}><DeleteIcon /></IconButton></div>}</article>) : <Typography color="text.secondary">No transactions yet. Add the first deposit to begin.</Typography>}</Paper>}<TransactionDialog editing={editing} isAdmin={canManage} onClose={() => { setOpen(false); setEditing(null) }} onSave={(data) => save.mutate(data)} open={open} saving={save.isPending} userName={user?.name ?? ''} /></section> }
function TransactionDialog({ editing, isAdmin, onClose, onSave, open, saving, userName }: { editing: Transaction | null; isAdmin: boolean; onClose: () => void; onSave: (data: TransactionInput) => void; open: boolean; saving: boolean; userName: string }) { const form = useForm<TransactionInput>({ resolver: zodResolver(schema), values: editing ? { person: editing.person, type: editing.type, amount: editing.amount, date: editing.date, mode: editing.mode, note: editing.note } : { ...defaultValues, person: isAdmin ? '' : userName } }); return <Dialog fullWidth maxWidth="sm" onClose={onClose} open={open}><DialogTitle>{editing ? 'Edit transaction' : 'Add transaction'}</DialogTitle><DialogContent><form className="transaction-form" id="transaction-form" onSubmit={form.handleSubmit(onSave)}><Controller control={form.control} name="person" render={({ field }) => <TextField {...field} disabled={!isAdmin} error={Boolean(form.formState.errors.person)} helperText={form.formState.errors.person?.message} label="Person" select>{isAdmin ? ['Sagar', 'Tejas'].map((person) => <MenuItem key={person} value={person}>{person}</MenuItem>) : <MenuItem value={userName}>{userName}</MenuItem>}</TextField>} /><Controller control={form.control} name="type" render={({ field }) => <TextField {...field} disabled={!isAdmin && field.value === TransactionType.Withdrawal} label="Type" select><MenuItem value={TransactionType.Deposit}>Deposit</MenuItem>{isAdmin && <MenuItem value={TransactionType.Withdrawal}>Withdrawal</MenuItem>}</TextField>} /><Controller control={form.control} name="amount" render={({ field }) => <TextField {...field} error={Boolean(form.formState.errors.amount)} helperText={form.formState.errors.amount?.message} label="Amount" type="number" />} /><Controller control={form.control} name="date" render={({ field }) => <TextField {...field} label="Date" type="date" />} /><Controller control={form.control} name="mode" render={({ field }) => <TextField {...field} label="Mode" select><MenuItem value={PaymentMode.OnlineTransfer}>Online Transfer</MenuItem><MenuItem value={PaymentMode.Cash}>Cash</MenuItem></TextField>} /><Controller control={form.control} name="note" render={({ field }) => <TextField {...field} error={Boolean(form.formState.errors.note)} helperText={form.formState.errors.note?.message || 'Required for withdrawals.'} label="Note" multiline minRows={2} />} /></form></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button disabled={saving} form="transaction-form" type="submit" variant="contained">Save</Button></DialogActions></Dialog> }
