import ConstructionOutlinedIcon from '@mui/icons-material/ConstructionOutlined'
import { Paper, Typography } from '@mui/material'
import type { ReactNode } from 'react'
export function PlaceholderPage({ title, description, children }: { title: string; description: string; children?: ReactNode }) { return <section className="page"><div><Typography component="h1" variant="h1">{title}</Typography><Typography className="description">{description}</Typography></div>{children ?? <Paper className="placeholder"><ConstructionOutlinedIcon color="primary" fontSize="large" /><Typography component="h2" variant="h2">Coming in a future milestone</Typography><Typography color="text.secondary">The page shell is ready. Data and interactions will be introduced in the planned feature milestone.</Typography></Paper>}</section> }
export function DashboardPage() { return <PlaceholderPage description="A clear view of the family ledger at a glance." title="Dashboard"><div className="summaries">{['Available balance', 'Total deposits', 'Total withdrawals'].map(label => <Paper className="summary" key={label}><Typography color="text.secondary" variant="body2">{label}</Typography><Typography component="p" variant="h2">—</Typography><Typography color="text.secondary" variant="body2">Awaiting data</Typography></Paper>)}</div><Paper className="placeholder"><Typography component="h2" variant="h2">Your ledger overview will appear here</Typography><Typography color="text.secondary">Connect the data source in Milestone 3 to see balances and statistics.</Typography></Paper></PlaceholderPage> }
export const TransactionsPage = () => <PlaceholderPage description="Record and review deposits and expenses for each family member." title="Transactions" />
export const CalendarPage = () => <PlaceholderPage description="Review daily deposits and expenses in a monthly calendar." title="Calendar" />
export const ReportsPage = () => <PlaceholderPage description="Filter and understand the family ledger over any date range." title="Reports" />
export const SettingsPage = () => <PlaceholderPage description="Manage app preferences and connected services." title="Settings" />
